
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AppRefreshingIndicator: typeof import("../app/components/AppRefreshingIndicator.vue")['default']
export const ArticleForm: typeof import("../app/components/admin/articles/ArticleForm.vue")['default']
export const ActionDropdown: typeof import("../app/components/app/ActionDropdown.vue")['default']
export const AlertMessage: typeof import("../app/components/app/AlertMessage.vue")['default']
export const AppBadge: typeof import("../app/components/app/AppBadge.vue")['default']
export const AppButton: typeof import("../app/components/app/AppButton.vue")['default']
export const AppCard: typeof import("../app/components/app/AppCard.vue")['default']
export const AppDropdown: typeof import("../app/components/app/AppDropdown.vue")['default']
export const AppInput: typeof import("../app/components/app/AppInput.vue")['default']
export const AppModal: typeof import("../app/components/app/AppModal.vue")['default']
export const AppSelect: typeof import("../app/components/app/AppSelect.vue")['default']
export const AppTextarea: typeof import("../app/components/app/AppTextarea.vue")['default']
export const ConfirmDialog: typeof import("../app/components/app/ConfirmDialog.vue")['default']
export const DataTable: typeof import("../app/components/app/DataTable.vue")['default']
export const EmptyState: typeof import("../app/components/app/EmptyState.vue")['default']
export const FilterBar: typeof import("../app/components/app/FilterBar.vue")['default']
export const OtpInput: typeof import("../app/components/app/OtpInput.vue")['default']
export const PageHeader: typeof import("../app/components/app/PageHeader.vue")['default']
export const PageLoadingBar: typeof import("../app/components/app/PageLoadingBar.vue")['default']
export const PageSkeleton: typeof import("../app/components/app/PageSkeleton.vue")['default']
export const SectionHeader: typeof import("../app/components/app/SectionHeader.vue")['default']
export const StatsCard: typeof import("../app/components/app/StatsCard.vue")['default']
export const TablePagination: typeof import("../app/components/app/TablePagination.vue")['default']
export const ToastContainer: typeof import("../app/components/app/ToastContainer.vue")['default']
export const AuthButton: typeof import("../app/components/auth/AuthButton.vue")['default']
export const AuthCard: typeof import("../app/components/auth/AuthCard.vue")['default']
export const AuthInput: typeof import("../app/components/auth/AuthInput.vue")['default']
export const AdminShell: typeof import("../app/components/dashboard/AdminShell.vue")['default']
export const AppBreadcrumbs: typeof import("../app/components/dashboard/AppBreadcrumbs.vue")['default']
export const AppHeader: typeof import("../app/components/dashboard/AppHeader.vue")['default']
export const AppShell: typeof import("../app/components/dashboard/AppShell.vue")['default']
export const AppSidebar: typeof import("../app/components/dashboard/AppSidebar.vue")['default']
export const CommandPalette: typeof import("../app/components/dashboard/CommandPalette.vue")['default']
export const NotificationDropdown: typeof import("../app/components/dashboard/NotificationDropdown.vue")['default']
export const UserDropdown: typeof import("../app/components/dashboard/UserDropdown.vue")['default']
export const DeleteMenuModal: typeof import("../app/components/menus/DeleteMenuModal.vue")['default']
export const MenuFormModal: typeof import("../app/components/menus/MenuFormModal.vue")['default']
export const MenuIcon: typeof import("../app/components/menus/MenuIcon.vue")['default']
export const ArticleCard: typeof import("../app/components/news/ArticleCard.vue")['default']
export const ArticleEmptyState: typeof import("../app/components/news/ArticleEmptyState.vue")['default']
export const BreakingNewsBanner: typeof import("../app/components/news/BreakingNewsBanner.vue")['default']
export const FeaturedArticleCard: typeof import("../app/components/news/FeaturedArticleCard.vue")['default']
export const FeaturedArticleHeroCard: typeof import("../app/components/news/FeaturedArticleHeroCard.vue")['default']
export const FeedFilterTabs: typeof import("../app/components/news/FeedFilterTabs.vue")['default']
export const NewArticleCard: typeof import("../app/components/news/NewArticleCard.vue")['default']
export const NewBreakingBanner: typeof import("../app/components/news/NewBreakingBanner.vue")['default']
export const NewEmptyState: typeof import("../app/components/news/NewEmptyState.vue")['default']
export const NewHeroCard: typeof import("../app/components/news/NewHeroCard.vue")['default']
export const NewSidebar: typeof import("../app/components/news/NewSidebar.vue")['default']
export const NewsSidebar: typeof import("../app/components/news/NewsSidebar.vue")['default']
export const ImportPermissionModal: typeof import("../app/components/permissions/ImportPermissionModal.vue")['default']
export const PublicFooter: typeof import("../app/components/public/PublicFooter.vue")['default']
export const PublicHeader: typeof import("../app/components/public/PublicHeader.vue")['default']
export const PublicSearchOverlay: typeof import("../app/components/public/PublicSearchOverlay.vue")['default']
export const AssignRolePermissionsModal: typeof import("../app/components/roles/AssignRolePermissionsModal.vue")['default']
export const CloneRoleModal: typeof import("../app/components/roles/CloneRoleModal.vue")['default']
export const ImportRoleModal: typeof import("../app/components/roles/ImportRoleModal.vue")['default']
export const DashboardPageMotion: typeof import("../app/components/transition/DashboardPageMotion.vue")['default']
export const MotionCard: typeof import("../app/components/transition/MotionCard.vue")['default']
export const Avatar: typeof import("../app/components/ui/Avatar.vue")['default']
export const Button: typeof import("../app/components/ui/Button.vue")['default']
export const Drawer: typeof import("../app/components/ui/Drawer.vue")['default']
export const Dropdown: typeof import("../app/components/ui/Dropdown.vue")['default']
export const DropdownItem: typeof import("../app/components/ui/DropdownItem.vue")['default']
export const IconButton: typeof import("../app/components/ui/IconButton.vue")['default']
export const Logo: typeof import("../app/components/ui/Logo.vue")['default']
export const SearchInput: typeof import("../app/components/ui/SearchInput.vue")['default']
export const Separator: typeof import("../app/components/ui/Separator.vue")['default']
export const Sidebar: typeof import("../app/components/ui/Sidebar.vue")['default']
export const Skeleton: typeof import("../app/components/ui/Skeleton.vue")['default']
export const ThemeToggle: typeof import("../app/components/ui/ThemeToggle.vue")['default']
export const CreateUserModal: typeof import("../app/components/users/CreateUserModal.vue")['default']
export const DeleteUserModal: typeof import("../app/components/users/DeleteUserModal.vue")['default']
export const EditUserModal: typeof import("../app/components/users/EditUserModal.vue")['default']
export const UserStatusBadge: typeof import("../app/components/users/UserStatusBadge.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAppRefreshingIndicator: LazyComponent<typeof import("../app/components/AppRefreshingIndicator.vue")['default']>
export const LazyArticleForm: LazyComponent<typeof import("../app/components/admin/articles/ArticleForm.vue")['default']>
export const LazyActionDropdown: LazyComponent<typeof import("../app/components/app/ActionDropdown.vue")['default']>
export const LazyAlertMessage: LazyComponent<typeof import("../app/components/app/AlertMessage.vue")['default']>
export const LazyAppBadge: LazyComponent<typeof import("../app/components/app/AppBadge.vue")['default']>
export const LazyAppButton: LazyComponent<typeof import("../app/components/app/AppButton.vue")['default']>
export const LazyAppCard: LazyComponent<typeof import("../app/components/app/AppCard.vue")['default']>
export const LazyAppDropdown: LazyComponent<typeof import("../app/components/app/AppDropdown.vue")['default']>
export const LazyAppInput: LazyComponent<typeof import("../app/components/app/AppInput.vue")['default']>
export const LazyAppModal: LazyComponent<typeof import("../app/components/app/AppModal.vue")['default']>
export const LazyAppSelect: LazyComponent<typeof import("../app/components/app/AppSelect.vue")['default']>
export const LazyAppTextarea: LazyComponent<typeof import("../app/components/app/AppTextarea.vue")['default']>
export const LazyConfirmDialog: LazyComponent<typeof import("../app/components/app/ConfirmDialog.vue")['default']>
export const LazyDataTable: LazyComponent<typeof import("../app/components/app/DataTable.vue")['default']>
export const LazyEmptyState: LazyComponent<typeof import("../app/components/app/EmptyState.vue")['default']>
export const LazyFilterBar: LazyComponent<typeof import("../app/components/app/FilterBar.vue")['default']>
export const LazyOtpInput: LazyComponent<typeof import("../app/components/app/OtpInput.vue")['default']>
export const LazyPageHeader: LazyComponent<typeof import("../app/components/app/PageHeader.vue")['default']>
export const LazyPageLoadingBar: LazyComponent<typeof import("../app/components/app/PageLoadingBar.vue")['default']>
export const LazyPageSkeleton: LazyComponent<typeof import("../app/components/app/PageSkeleton.vue")['default']>
export const LazySectionHeader: LazyComponent<typeof import("../app/components/app/SectionHeader.vue")['default']>
export const LazyStatsCard: LazyComponent<typeof import("../app/components/app/StatsCard.vue")['default']>
export const LazyTablePagination: LazyComponent<typeof import("../app/components/app/TablePagination.vue")['default']>
export const LazyToastContainer: LazyComponent<typeof import("../app/components/app/ToastContainer.vue")['default']>
export const LazyAuthButton: LazyComponent<typeof import("../app/components/auth/AuthButton.vue")['default']>
export const LazyAuthCard: LazyComponent<typeof import("../app/components/auth/AuthCard.vue")['default']>
export const LazyAuthInput: LazyComponent<typeof import("../app/components/auth/AuthInput.vue")['default']>
export const LazyAdminShell: LazyComponent<typeof import("../app/components/dashboard/AdminShell.vue")['default']>
export const LazyAppBreadcrumbs: LazyComponent<typeof import("../app/components/dashboard/AppBreadcrumbs.vue")['default']>
export const LazyAppHeader: LazyComponent<typeof import("../app/components/dashboard/AppHeader.vue")['default']>
export const LazyAppShell: LazyComponent<typeof import("../app/components/dashboard/AppShell.vue")['default']>
export const LazyAppSidebar: LazyComponent<typeof import("../app/components/dashboard/AppSidebar.vue")['default']>
export const LazyCommandPalette: LazyComponent<typeof import("../app/components/dashboard/CommandPalette.vue")['default']>
export const LazyNotificationDropdown: LazyComponent<typeof import("../app/components/dashboard/NotificationDropdown.vue")['default']>
export const LazyUserDropdown: LazyComponent<typeof import("../app/components/dashboard/UserDropdown.vue")['default']>
export const LazyDeleteMenuModal: LazyComponent<typeof import("../app/components/menus/DeleteMenuModal.vue")['default']>
export const LazyMenuFormModal: LazyComponent<typeof import("../app/components/menus/MenuFormModal.vue")['default']>
export const LazyMenuIcon: LazyComponent<typeof import("../app/components/menus/MenuIcon.vue")['default']>
export const LazyArticleCard: LazyComponent<typeof import("../app/components/news/ArticleCard.vue")['default']>
export const LazyArticleEmptyState: LazyComponent<typeof import("../app/components/news/ArticleEmptyState.vue")['default']>
export const LazyBreakingNewsBanner: LazyComponent<typeof import("../app/components/news/BreakingNewsBanner.vue")['default']>
export const LazyFeaturedArticleCard: LazyComponent<typeof import("../app/components/news/FeaturedArticleCard.vue")['default']>
export const LazyFeaturedArticleHeroCard: LazyComponent<typeof import("../app/components/news/FeaturedArticleHeroCard.vue")['default']>
export const LazyFeedFilterTabs: LazyComponent<typeof import("../app/components/news/FeedFilterTabs.vue")['default']>
export const LazyNewArticleCard: LazyComponent<typeof import("../app/components/news/NewArticleCard.vue")['default']>
export const LazyNewBreakingBanner: LazyComponent<typeof import("../app/components/news/NewBreakingBanner.vue")['default']>
export const LazyNewEmptyState: LazyComponent<typeof import("../app/components/news/NewEmptyState.vue")['default']>
export const LazyNewHeroCard: LazyComponent<typeof import("../app/components/news/NewHeroCard.vue")['default']>
export const LazyNewSidebar: LazyComponent<typeof import("../app/components/news/NewSidebar.vue")['default']>
export const LazyNewsSidebar: LazyComponent<typeof import("../app/components/news/NewsSidebar.vue")['default']>
export const LazyImportPermissionModal: LazyComponent<typeof import("../app/components/permissions/ImportPermissionModal.vue")['default']>
export const LazyPublicFooter: LazyComponent<typeof import("../app/components/public/PublicFooter.vue")['default']>
export const LazyPublicHeader: LazyComponent<typeof import("../app/components/public/PublicHeader.vue")['default']>
export const LazyPublicSearchOverlay: LazyComponent<typeof import("../app/components/public/PublicSearchOverlay.vue")['default']>
export const LazyAssignRolePermissionsModal: LazyComponent<typeof import("../app/components/roles/AssignRolePermissionsModal.vue")['default']>
export const LazyCloneRoleModal: LazyComponent<typeof import("../app/components/roles/CloneRoleModal.vue")['default']>
export const LazyImportRoleModal: LazyComponent<typeof import("../app/components/roles/ImportRoleModal.vue")['default']>
export const LazyDashboardPageMotion: LazyComponent<typeof import("../app/components/transition/DashboardPageMotion.vue")['default']>
export const LazyMotionCard: LazyComponent<typeof import("../app/components/transition/MotionCard.vue")['default']>
export const LazyAvatar: LazyComponent<typeof import("../app/components/ui/Avatar.vue")['default']>
export const LazyButton: LazyComponent<typeof import("../app/components/ui/Button.vue")['default']>
export const LazyDrawer: LazyComponent<typeof import("../app/components/ui/Drawer.vue")['default']>
export const LazyDropdown: LazyComponent<typeof import("../app/components/ui/Dropdown.vue")['default']>
export const LazyDropdownItem: LazyComponent<typeof import("../app/components/ui/DropdownItem.vue")['default']>
export const LazyIconButton: LazyComponent<typeof import("../app/components/ui/IconButton.vue")['default']>
export const LazyLogo: LazyComponent<typeof import("../app/components/ui/Logo.vue")['default']>
export const LazySearchInput: LazyComponent<typeof import("../app/components/ui/SearchInput.vue")['default']>
export const LazySeparator: LazyComponent<typeof import("../app/components/ui/Separator.vue")['default']>
export const LazySidebar: LazyComponent<typeof import("../app/components/ui/Sidebar.vue")['default']>
export const LazySkeleton: LazyComponent<typeof import("../app/components/ui/Skeleton.vue")['default']>
export const LazyThemeToggle: LazyComponent<typeof import("../app/components/ui/ThemeToggle.vue")['default']>
export const LazyCreateUserModal: LazyComponent<typeof import("../app/components/users/CreateUserModal.vue")['default']>
export const LazyDeleteUserModal: LazyComponent<typeof import("../app/components/users/DeleteUserModal.vue")['default']>
export const LazyEditUserModal: LazyComponent<typeof import("../app/components/users/EditUserModal.vue")['default']>
export const LazyUserStatusBadge: LazyComponent<typeof import("../app/components/users/UserStatusBadge.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
